name: Spellcheck Action
on: pull_request*

jobs:
  build:
    name: Get all changed markdown files
    runs-on: ubuntu-latest

    steps:
    - uses: tj-actions/changed-files@v45
      id: changed_files
      with:
        files: |
           **.md

    - name: Run Spellcheck
      id: spellcheck
      uses: rojopolis/spellcheck-github-actions@v0
      with:
        task_name: Markdown
        source_files: ${{ steps.changed_files.outputs.all_changed_files }}