name: Publish Dragonfly Wiki to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    - name: Get all changed markdown files
      uses: tj-actions/changed-files@v45
      id: changed_files
      with:
        files: |
           **.md

    - name: Run Spellcheck
      id: spellcheck
      uses: rojopolis/spellcheck-github-actions@v0
      with:
        task_name: Markdown
        source_files: ${{ steps.changed_files.outputs.all_changed_files }}

  publish:
    name: Publish to retype branch
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - uses: retypeapp/action-build@latest
      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true